### ISSUE TITLE
Bedrock players detected as Java players.

### ISSUE THREAD

**Issue by Clyde-Timonera** [GeyserExtras/GeyserExtras#1]
![image](https://github.com/GeyserExtras/GeyserExtras/assets/78290310/c3de99ee-0b12-4bdc-ad75-2b10981805df)
I use a proxy setup on my server and I wanted to test some features just to realize that none of them works because it mistakens people as Java players, plugin and purpur server is up to date, geyser and floodgate aswell.

**Comment by letsgoawaydev** [comment]
make sure forward-floodgate-data or what ever the option name is is set to true in floodgates config

**Comment by Clyde-Timonera** [comment]
Hi, do you mean send-floodgate-data? if so that fixed it. Thanks.

**Comment by letsgoawaydev** [comment]
> Hi, do you mean send-floodgate-data? if so that fixed it. Thanks.

yes, your welcome :) i will be adding proper instructions to the wiki soon

**Comment by letsgoawaydev** [comment]
https://github.com/GeyserExtras/GeyserExtras/wiki/Getting-started done :)

**Comment by Clyde-Timonera** [comment]
Nice, that should help a lot of people.
