### ISSUE TITLE
Aternos

### ISSUE THREAD

**Issue by AlLCWGithub** [GeyserExtras/GeyserExtras#7]
I use aternos, when I put resources packs into the folder optionalpacks/,  using the command /get will say there's an internal error, what do I do?
![Screenshot_20240811_190652_Minecraft]

(https://github.com/user-attachments/assets/8909215d-c5dd-414e-ac39-e10bc005f527)

**Comment by letsgoawaydev** [comment]
can you send logs?

**Comment by AlLCWGithub** [comment]
Sure
https://mclo.gs/gOXHsV4
Btw there are two of the logs, I think they are the same thing.

**Comment by AlLCWGithub** [comment]
Btw are the resources pack meant to be bedrock ones?

**Comment by AlLCWGithub** [comment]
Logs do say they are invalid :/

**Comment by letsgoawaydev** [comment]
> Btw are the resources pack meant to be bedrock ones?

yes, java ones will not work

**Comment by AlLCWGithub** [comment]
So what's the point of a optionalpacks?
Is it so java can use?

**Comment by AlLCWGithub** [comment]
And not the other way round

**Comment by letsgoawaydev** [comment]
its so bedrock players can load packs if they want by doing /ge and choosing Optional Packs

Console players cant load custom resource packs, so this feature was created to work around it

Place .mcpack files inside of the plugins optionalpacks folder

**Comment by AlLCWGithub** [comment]
Oh ok, and that means MCADDONS don't work unfortunately right?

**Comment by letsgoawaydev** [comment]
unfortunately no because behaviour packs are loaded by the bedrock server, and java cant load it

.mcpacks that are resource packs will work

**Comment by AlLCWGithub** [comment]
Alright thanks for helping me!

**Comment by AlLCWGithub** [comment]
Uhhm the optionalpacks option doesn't exist???

**Comment by letsgoawaydev** [comment]
You need to restart the server if you have just added packs, then do /ge on Bedrock and go to Optional Packs

**Comment by AlLCWGithub** [comment]
Alright, but is it just me or geyser has a packs feature inbuilt. But ok I'll reload the server

**Comment by letsgoawaydev** [comment]
optional packs allows players to toggle resource packs for them selves, where as geyser's packs folder requires everyone to load the same packs

**Comment by AlLCWGithub** [comment]
Ah ok, that makes sense, really genius to give them an option, me as the average consumer would never understand how that works
